### ISSUE TITLE
Rejecting GPS permissions on Android 12 kills the demo app permanently 

### ISSUE THREAD

**Issue by Jaceken** [ably/asset-tracking-android-rider-app-demo#11]
:red_circle:  **Issue**
After rejecting the GPS permission popup for the second time - the app won't start :scream_cat: 
:point_up: Occurs only on Android 12. Tested also using Android 10 - in this case, the OS behavior is different.

🏞️ **Environment**
Tested using app v.
Android Rider app v1.0(17)

:phone: P120 Samsung Galaxy M51 A. 10
:phone: Google Pixel 5 Android 12

🦶 **Steps to reproduce**

:one: First scenario[using Pixel A. 12]:

1. install the app
1. when asked about GPS permissions - don't allow them. The app will be closed.
1. open the app again
1. when asked again about the permissions - reject them again. The app will be closed.
1. try to open the app again
:x: Application will be closed automatically.

:one: First scenario[using Samsung A. 10]:

1. install the app
1. when asked about GPS permissions - don't allow them. The app will be closed.
1. open the app again
1. when asked again about the permissions - reject them again. The app will be closed.
1. try to open the app again
:white_check_mark: Application will be opened again and permissions popup will be displayed again(as GPS was rejected before twice) 

:bulb: 
I noticed that in Android 10 there was an option to select "Reject permissions and don't ask again". 
In Android 12 option was missing. After the second rejection, the OS "decided" not to ask the user again about the permissions and the app was not opening.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2384) by [Unito](https://www.unito.io)

**Comment by davyskiba** [comment]
Closing the app when location permission is denied is an implementation shortcut on my side to avoid handling the unhappy path that is not necessarily related to asset tracking SDK and just close the app.

Unfortunately handling such cases as repetitive permission denial in a different manner by different OS vendors is one of the Android world wonders 😞 

We can add more stuff around it, not sure if it serve the demo app purpose 🤔

**Comment by deanna-lad** [comment]
@QuintinWillison what are your thoughts on this?

**Comment by QuintinWillison** [comment]
I think I may have mentioned this in our standup this morning, but if this is something we feel we can't do more elegantly then the resolution for this issue should be to add some description of this limitation to the readme. Probably a "Known Limitations" H2 would be appropriate.
