### ISSUE TITLE
Unify and document tracking resolutions with iOS 

### ISSUE THREAD

**Issue by davyskiba** [ably/asset-tracking-android-rider-app-demo#16]
Ensure that apps on both platforms use the same values for resolution strategy and document them in README

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2420) by [Unito](https://www.unito.io)

**Comment by davyskiba** [comment]
Android Raider app is currently using the following as the default publisher resolution
```  
Resolution(Accuracy.BALANCED, desiredInterval = 1000L, minimumDisplacement = 1.0)
```

and for trackable, we are using:

```
private fun getOrderResolutionConstraints() =
        DefaultResolutionConstraints(
            resolutions = getResolutionSet(),
            proximityThreshold = DefaultProximity(spatial = 1.0),
            batteryLevelThreshold = 15.0f,
            lowBatteryMultiplier = 5.0f
        )

    private fun getResolutionSet() =
        DefaultResolutionSet(
            farWithoutSubscriber = Resolution(
                accuracy = Accuracy.MINIMUM,
                desiredInterval = 2000L,
                minimumDisplacement = 100.0
            ),
            farWithSubscriber = Resolution(
                accuracy = Accuracy.BALANCED,
                desiredInterval = 1000L,
                minimumDisplacement = 10.0
            ),
            nearWithoutSubscriber = Resolution(
                accuracy = Accuracy.BALANCED,
                desiredInterval = 1000L,
                minimumDisplacement = 10.0
            ),
            nearWithSubscriber = Resolution(
                accuracy = Accuracy.HIGH,
                desiredInterval = 500L,
                minimumDisplacement = 1.0
            )
        )
```

I would increase `minimumDisplacement` for the default resolution to at least 1000.0 and the `proximityThreshold` for trackable constraints to 1000.0
@JakubJankowski @Jaceken, what do you think about those?

**Comment by davyskiba** [comment]
@arturjaworski ☝️

**Comment by JakubJankowski** [comment]
We might also want to bump the battery level threshold quite a bit, let's say to 50, to make it easier to test?

**Comment by JakubJankowski** [comment]
Skimmed through the code quickly, I don't think we're specifying foreground/background i the customer app. But Artur knows this codebase much better then me, so I'd wait for him to chip in.

**Comment by arturjaworski** [comment]
@davyskiba In customer app we present user some text inputs to define the resolution. There is no default values
![Simulator Screen Shot - iPhone 13 Pro - 2022-07-06 at 14 47 57](https://user-images.githubusercontent.com/1076431/177553681-c87f88e3-ec2f-401d-a60e-bba66877cf06.png)
.

**Comment by davyskiba** [comment]
Not sure where to go with desired resolution in both cases in the customer app:
 - input vs. hardcoded 
 - single setting vs. foreground/background 

@QuintinWillison, do you have any preferences?

**Comment by davyskiba** [comment]
I think that we should go with a hardcoded configuration because those demo apps should rather function as a usage showcase than a testing app we should go.

[Production milestone](https://github.com/ably/asset-tracking-demos/blob/main/app-requirements.md#milestone-2-production) specifies we should use different configurations based on user's behaviour:
>Should configure the resolution based on the user’s behaviour (if the app is in the background, or the user is looking at a different page: we don’t need a high resolution)
