### ISSUE TITLE
Store and share rider's location history data 

### ISSUE THREAD

**Issue by Jaceken** [ably/asset-tracking-android-rider-app-demo#29]
:bulb:  **Task**
To make issues analysis easier, we should be able to store and share location history(saved during test execution).

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2462) by [Unito](https://www.unito.io)
┆Link To Issue: https://ably.atlassian.net/browse/SDK-2462

**Comment by davyskiba** [comment]
@JakubJankowski @arturjaworski @Jaceken do you have a specific idea where do we want to put those?
In a real-life production app, this would probably end up in some kind of debug drawer that's available only in debug/QA builds 🤔 
Maybe we can add it to the drawer but make it available in release builds?

**Comment by Jaceken** [comment]
From a QA perspective, that's a great idea 😍
