### ISSUE TITLE
Publish rate frequency depends on the device manufacturer

### ISSUE THREAD

**Issue by Jaceken** [ably/asset-tracking-android-rider-app-demo#32]
:red_circle:  **Issue**
Android Publisher app updates localization with different frequencies for different device manufacturers. 
Battery level, proximity to destination, and channel subscription state were the same for both devices. 

🏞️ **Environment**
Tested using  Android Customer app v1.0(29)
P120 Samsung Galaxy M51 A. 10
Google Pixel 5 Android 12

Test conditions:

* Spotted during LONG RUN test(~8h)
* Network: 5G
* Batteries were fully charged and devices were connected to the power supply 
* No destination point was selected
* For both devices channel was subscribed 

🦶 **Steps to reproduce**

1. Start publisher app
1. Add trackable ID
1. Observe the Enhanced Location Update Messages(Dev Console)

:x: Messages from Pixel are updated with twice the frequency as from Samsung.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2465) by [Unito](https://www.unito.io)

**Comment by davyskiba** [comment]
@Jaceken could you attach an export of logs from Dev Console?

**Comment by davyskiba** [comment]
This issue was discussed in [this slack thread](https://ably-real-time.slack.com/archives/C03HDRGLZ1B/p1658215372510449)

**Comment by davyskiba** [comment]
We can no longer reproduce the issue - closing, discussion with Mapbox to be concluded on [this issue.](https://github.com/mapbox-collab/Ably-DH-Collab/issues/14)
